/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Dev
 */
public class Main extends javax.swing.JFrame implements IDashboard {
    
    private final MainPresenter presenter = new MainPresenter(this);

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setTitle("ClassRoomAnalytics");
        ComboBoxModel<String> dataHoje = new javax.swing.DefaultComboBoxModel<>(new String[] { LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))});
        comboBoxDataInicio.setModel(dataHoje);
        comboBoxDataFinal.setModel(dataHoje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tableEstaus = new javax.swing.JTable();
        importaArquivoButton = new javax.swing.JToggleButton();
        botaoExibirTexto = new javax.swing.JButton();
        comboBoxDataInicio = new javax.swing.JComboBox<>();
        comboBoxDataFinal = new javax.swing.JComboBox<>();
        checkBoxexibirTexto = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableEstaus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableEstaus);

        importaArquivoButton.setText("Importar Arquivo");
        importaArquivoButton.setFocusable(false);
        importaArquivoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        importaArquivoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        importaArquivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importaArquivoButtonActionPerformed(evt);
            }
        });

        botaoExibirTexto.setText("Exibir Texto");
        botaoExibirTexto.setEnabled(false);
        botaoExibirTexto.setFocusable(false);
        botaoExibirTexto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoExibirTexto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoExibirTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExibirTextoActionPerformed(evt);
            }
        });

        comboBoxDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDataInicioActionPerformed(evt);
            }
        });

        comboBoxDataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDataFinalActionPerformed(evt);
            }
        });

        checkBoxexibirTexto.setText("Exibir Texto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(comboBoxDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(importaArquivoButton)
                            .addGap(18, 18, 18)
                            .addComponent(checkBoxexibirTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(botaoExibirTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(239, 483, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botaoExibirTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkBoxexibirTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(importaArquivoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importaArquivoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importaArquivoButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fileChooser.setFileFilter(new SetFileFilter()); //especifica a extenção
        int estadoDeSelecao = fileChooser.showOpenDialog(this); 
        if (estadoDeSelecao == JFileChooser.CANCEL_OPTION) {
            return; 
        }
        File arquivoSelecionado = fileChooser.getSelectedFile();        
        if (presenter.esUmArquivoValido(arquivoSelecionado)) {
            try {            
                presenter.processarDadosDoArquivo(arquivoSelecionado);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Erro no arquivo","Erro no arquivo", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Nome inválido","Nome inválido", JOptionPane.ERROR_MESSAGE);
        }
        presenter.atualizarTabelaDeContato();
    }//GEN-LAST:event_importaArquivoButtonActionPerformed

    private void botaoExibirTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExibirTextoActionPerformed
         presenter.exibirTextoConversa(true);
    }//GEN-LAST:event_botaoExibirTextoActionPerformed

    private void comboBoxDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDataInicioActionPerformed
        this.filtrarConversaPelaData();
    }//GEN-LAST:event_comboBoxDataInicioActionPerformed

    private void comboBoxDataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDataFinalActionPerformed
        this.filtrarConversaPelaData();
    }//GEN-LAST:event_comboBoxDataFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExibirTexto;
    private javax.swing.JCheckBox checkBoxexibirTexto;
    private javax.swing.JComboBox<String> comboBoxDataFinal;
    private javax.swing.JComboBox<String> comboBoxDataInicio;
    private javax.swing.JToggleButton importaArquivoButton;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableEstaus;
    // End of variables declaration//GEN-END:variables

    @Override
    public void atualizarCampoEditor(String texto) {
        JanelaEditor janelaEditor = new JanelaEditor();
        janelaEditor.setTitle("Texto Importado");
        janelaEditor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        janelaEditor.setVisible(true);
        janelaEditor.atualizarCampoEditor(texto);   
        //campoEditorPane.setText(texto);        
    }

    
    @Override
    public void atualizarTabelaEstatisticaContatos(Object [][] matrizDeEstatisticaContatos, String [] nomeColunas ) {
        tableEstaus.setModel(new javax.swing.table.DefaultTableModel(
                matrizDeEstatisticaContatos,nomeColunas            
        ));
        
        jScrollPane3.setViewportView(tableEstaus);
    }

    @Override
    public void atualizarBotaoFiltro(String[] datas, boolean ativar) {
        this.botaoExibirTexto.setEnabled(ativar);
        this.comboBoxDataInicio.setModel(new DefaultComboBoxModel<>(datas));
        this.comboBoxDataFinal.setModel(new DefaultComboBoxModel<>(datas));
    }

    @Override
    public boolean getEstatusCampoEditor() {
        return checkBoxexibirTexto.isSelected();
    }
    
    public void filtrarConversaPelaData(){
        String dataInicio = comboBoxDataInicio.getSelectedItem().toString();
        String dataFim = comboBoxDataFinal.getSelectedItem().toString();
        presenter.atualizarTabelaDeContato(dataInicio, dataFim);
    }
}
