/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dev
 */
public class Main extends javax.swing.JFrame implements IDashboard {
    
    private final MainPresenter presenter = new MainPresenter(this);

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tableEstaus = new javax.swing.JTable();
        importaArquivoButton = new javax.swing.JToggleButton();
        botaoTeste = new javax.swing.JButton();
        campoData = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableEstaus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableEstaus);

        importaArquivoButton.setText("Importar Arquivo");
        importaArquivoButton.setFocusable(false);
        importaArquivoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        importaArquivoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        importaArquivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importaArquivoButtonActionPerformed(evt);
            }
        });

        botaoTeste.setText("Teste");
        botaoTeste.setFocusable(false);
        botaoTeste.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoTeste.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTesteActionPerformed(evt);
            }
        });

        campoData.setText("dia/mês/ano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(importaArquivoButton)
                        .addGap(18, 18, 18)
                        .addComponent(botaoTeste))
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(483, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(importaArquivoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importaArquivoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importaArquivoButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fileChooser.setFileFilter(new SetFileFilter()); //especifica a extenção
        int estadoDeSelecao = fileChooser.showOpenDialog(this); 
        if (estadoDeSelecao == JFileChooser.CANCEL_OPTION) {
            return; 
        }
        File arquivoSelecionado = fileChooser.getSelectedFile();        
        if (presenter.esUmArquivoValido(arquivoSelecionado)) {
            try {            
                presenter.processarDadosDoArquivo(arquivoSelecionado);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Erro no arquivo","Erro no arquivo", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Nome inválido","Nome inválido", JOptionPane.ERROR_MESSAGE);
        }
        presenter.atualizarTabelaDeContato("");
    }//GEN-LAST:event_importaArquivoButtonActionPerformed

    private void botaoTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTesteActionPerformed
        
        //javax.swing.SpinnerDateModel
    // TODO add your handling code here:
    }//GEN-LAST:event_botaoTesteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoTeste;
    private javax.swing.JTextField campoData;
    private javax.swing.JToggleButton importaArquivoButton;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableEstaus;
    // End of variables declaration//GEN-END:variables

    @Override
    public void atualizarCampoEditor(String texto) {
        JanelaEditor janelaEditor = new JanelaEditor();
        janelaEditor.setTitle("Texto Importado");
        janelaEditor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        janelaEditor.setVisible(true);
        janelaEditor.atualizarCampoEditor(texto);   
        //campoEditorPane.setText(texto);        
    }

    
    @Override
    public void atualizarTabelaEstatisticaContatos(Object [][] matrizDeEstatisticaContatos, String [] nomeColunas ) {
        tableEstaus.setModel(new javax.swing.table.DefaultTableModel(
                matrizDeEstatisticaContatos,nomeColunas            
        ));
        
        jScrollPane3.setViewportView(tableEstaus);
    }
}
